### PR TITLE
Added updated ER diagram

### PR DESCRIPTION
**Pull request by vikhyat187**

### CODE REVIEW

**Review by prakashchoudhary07 — COMMENTED** [review]
In the feature flag model, 
`flag_name` can be made as `name`, same with the `flag_description` as `description`

What are your thoughts, on having a status field, `status: ENABLED` or `status: DISABLED`

In the user model, `User name` should be a single word, `username`

In the feature flag user mapping,
`User Id`, should be a single word `userId`

And do you think we need `createdBy` and `updatedBy` as we will be maintaining a log so we will get those details from there, what are you thoughts on this one

**Comment by vikhyat187** [comment]
> In the feature flag model,
flag_name can be made as name, same with the flag_description as description

Sure will change that.

> What are your thoughts, on having a status field, status: ENABLED or status: DISABLED, in feature flag model

 Should I change it to ENUM like status in FF-user mapping table aswell @prakashchoudhary07 ?
 
 > In the user model, User name should be a single word, username

Yes it is the same `username` just I've represented, will change

> In the feature flag user mapping,
User Id, should be a single word userId

Sure

> And do you think we need createdBy and updatedBy in feature flag user mapping as we will be maintaining a log so we will get those details from there, what are you thoughts on this on

Inline lets have it from the logs, so we will have updatedAt and createdAt in the FF-user mapping table to query the FF-User which are created after 2nd Jan let's say.

**Review by prakashchoudhary07 — APPROVED** [review]
status is an ENUM right

**Comment by vikhyat187** [comment]
Yes its an enum, was not sure how its implemented in other languages than Java, so wrote string.

**Pull request merged**
